### ISSUE TITLE
Include the commit SHA in the dependency table

### ISSUE THREAD

**Issue by dinakar29** [openpharma/staged.dependencies#108]
Including the git SHA (either long, or short) in the staged dependency table will provide the necessary information to debug any issues.

Use case:

I am testing my package against the `pre-release` branch of upstream packages, and would like to know which commit hash of the upstream packages is being used in the tests.

**Comment by nikolas-burkoff** [comment]
@waddella - this should be easy to do - shall I go ahead and add it into the project and do it?
