### ISSUE TITLE
Remove `--no-manual` default flag in `build_check_install` and stick to the defaults

### ISSUE THREAD

**Issue by pawelru** [openpharma/staged.dependencies#115]
In order to test package fully I do want to remove --no-manual flag. Currently it allows to push erroneous TeX code that could be easily identified.

**Comment by nikolas-burkoff** [comment]
R CMD INSTALL by RStudio uses :

--no-multiarch and --with-keep.source  so these should be defaults and @waddella would like --install-tests added as well.

And remove --no-manual


In check downstream and build check install
