### ISSUE TITLE
propose direct dependencies

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#17]
Add `update_dependencies` from the dependency graph (via `DESCRIPTION`) so that for every package we can list the complete distance 1 downstream & upstream packages. Please also add a distance to the dependency table

**Comment by waddella** [comment]
@maximilianmordig you can start with something as follows:

```r
propose_staged_dependencies_config <- function(project = ".") {
  tbl <- dependency_table(project)

  tbl$package <- vapply(strsplit(tbl$repo, "/", fixed = TRUE), tail, character(1), 1)
  
  cur <- tbl[tbl$type == "current", ]
  nrow(cur) == 1 || stop("could not find current repo")

  fdesc <- file.path(project, "DESCRIPTION")
  dsc <- desc::desc(fdesc)

  pkgs <- dsc$get_deps()$package

  # get direct upstream
  internal_pkgs <- tbl[pkgs %in% tbl$package, ]
  
  # get direct downstream
  
  # create a new staged_dependencies.yaml file at
  yaml::write_yaml(new_sd, file = file.path(project, "staged_dependencies.yaml"))

}

```

**Comment by waddella** [comment]
@maximilianmordig I have asked @pawelru to do this issue to learn more about `staged.dependencies`

**Comment by waddella** [comment]
we need the a distance column in the dependency table based on `DESCRIPTION`

**Comment by pawelru** [comment]
Hi all. I had a chance to look into this and this is my outcome:
```
get_descendants_distance <- function(parents_to_children, node) {
  internal_recursive_fun <- function(parents_to_children, node, distance = 0L) {
    if (is.null(parents_to_children[[node]])) {
      return()
    }
    c(
      lapply(parents_to_children[[node]], list, distance + 1L),
      unlist(lapply(parents_to_children[[node]], internal_recursive_fun, parents_to_children = parents_to_children, distance = distance + 1L), recursive = FALSE)
    )
  }
  internal_recursive_fun(parents_to_children, node) %>%
    c(stringsAsFactors = FALSE) %>%
    do.call(rbind.data.frame, .) %>%
    setNames(c("id", "distance")) %>%
    group_by(id) %>%
    summarise(distance = min(distance))
}
```

It should be run on internal `deps` variable. However, this is being determined by reading `.staged.dependency.yaml` files for all repos - not the `DESCRIPTION` file as written in the last comment

**Comment by maximilianmordig** [comment]
I don't find it clear what you mean by distance 1 packages. This assumes that each package is clean (according to R CMD check) so that only necessary upstream dependencies are listed in the DESCRIPTION file. Then, all packages listed in Imports or Depends in the DESCRIPTION file are distance 1 upstream packages. For the downstream packages of a package, we can go through all downstream packages according to the `.staged.dependencies.yaml` and check if they list the package as a dependency in the DESCRIPTION.
Is this what you meant with this issue?

**Comment by nikolas-burkoff** [comment]
@maximilianmordig  So I _think_ if you only want direct dependencies then yes you can do what you suggest (and it of course relies on the staged_dependencies.yaml capturing all the packages you are interested in).

@waddella the issue says we only need this - or are you expecting to be able to say show me the dependencies with distance < x for some x in which case we'd need a distance

**Comment by waddella** [comment]
lets discuss it in our meeting today

**Comment by nikolas-burkoff** [comment]
So I think this is what we need (simplified pseudo code here):

```
get_dependency_structure <- function(starting_repo){
  
  repos_to_explore <- list(starting_repo)
  repos_explored <- list()
  
  R_deps <- named list() #dependencies from DESCRIPTION file go here 
  
  while repos_to_explore not empty:
  
    current_repo <- repos_to_explore[1]
    
    checkout/copy repo into cache
    
    current_staged_deps <- deps in current_repo staged.yaml file
    append all current_staged_deps not in repos_to_explore or repos_explored into repos_to_explore
    
    R_deps[current_repo] <- suggest, imports and depends from current_repo description file   
    remove current_repo from repos_to_explore
  
  for all R_deps remove values not in repos_explored
  
  # Now have a list of internal dependencies repos_explored and the true child->parent relationships
  # in R_deps 
  
  R_deps <- topological_sort(R_deps)
  
  #use standard graph techniques to generate table which includes distances from starting_repo
  #(if relationship is other then distance will be NA and automation shouldn't check these repos out
  #when testing starting_repo)
  return(deps_table)
}

update_stage_dep_yaml_with_direct_deps <- function(project = "."){
  dep_structure <- get_dependency_structure()
  
  current_repo <- dep_structure[dep_structure$type == "current"]
  upstream_repos <- dep_structur[dep_structure$type == "upstream" & distance == 1]
  downstream_repos <- dep_structur[dep_structure$type == "downstream" & distance == 1]

  write_yaml(current_repo, upstream_repos, downstream_repos)  
}
```

**Comment by waddella** [comment]
that is fine, I would still use the downstream info in the `staged_dependency.yaml` file if it exists.
