### ISSUE TITLE
Failure on main: `desc` package missing

### ISSUE THREAD

**Issue by Melkiades** [openpharma/staged.dependencies#174]
`Error in loadNamespace(x) : there is no package called ‘desc’`

Tagging @asbates as your commit is last. It should be a fast-fix

**Comment by asbates** [comment]
@cicdguy I think this is the same error as with #171

**Comment by cicdguy** [comment]
@Melkiades - Which workflow run did this issue manifest in?

**Comment by Melkiades** [comment]
> @Melkiades - Which workflow run did this issue manifest in?

https://github.com/openpharma/staged.dependencies/actions/runs/3965924647/jobs/6796153584

It is on main (check)

**Comment by cicdguy** [comment]
Got it, as @asbates said it's probably related to an older issue. Will try to fix it asap.
