### ISSUE TITLE
dependency_graph bug

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#20]
I get:

```
> staged.dependencies::dependency_graph()
 Error: Problem with `mutate()` column `title`.
ℹ `title = get_edge_tooltip(.data$from, .data$to, .data$listed_by)`.
x `title` must return compatible vectors across groups
ℹ Result type for group 1 (from = "NEST/goshawk @ https://github.roche.com", to = "NEST/utils.nest @ https://github.roche.com"): <character>.
ℹ Result type for group 16 (from = "NEST/tern @ https://github.roche.com", to = "NEST/scda @ https://github.roche.com"): <list>.
Run `rlang::last_error()` to see where the error occurred. 
```

**Comment by maximilianmordig** [comment]
Please provide MWE to reproduce.

**Comment by waddella** [comment]
please take the internal `utils.nest` package on `insightsengineering` organization and test the `staged.dependency` package against that setup. There is currently though another issue among all the internal dependencies there that needs to be fixed (maybe start with the propose dependency issue).

**Comment by waddella** [comment]
in `tlgdown` I get
![image](https://user-images.githubusercontent.com/7786462/127660592-b7be0dac-abcb-4bc0-b05a-ef99ae38cbaa.png)

**Comment by pawelru** [comment]
It's this line of code: https://github.com/openpharma/staged.dependencies/blob/main/R/dependencies.R#L576
need to change that to return character
