### ISSUE TITLE
repeated dependency issue

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#21]
I ran into the issue:

```
Error in install_repo_add_sha(repo_dir) : 
  The git directory /home/users/waddella/.staged.dependencies/packages_cache/NEST_test.nest_681a713a88fd31f16f5c7a97bc0d5592 contains changes.
Calls: sourceWithProgress ... eval -> do.call -> <Anonymous> -> install_repo_add_sha
Execution halted
```
and when I check the repo I get

![image](https://user-images.githubusercontent.com/7786462/123940418-7751b800-d999-11eb-86a7-d0c5b8a85ed6.png)

and in particular with `git diff`

![image](https://user-images.githubusercontent.com/7786462/123940609-a23c0c00-d999-11eb-8cb0-475e7322e3c8.png)

Can you please run `git reset --hard origin/<branch>` to avoid this issue

**Comment by maximilianmordig** [comment]
Should not be necessary since using `git checkout` with `force`. Please provide MWE to reproduce.

**Comment by waddella** [comment]
please take the internal `utils.nest` package on `insightsengineering` organization and test the `staged.dependency` package against that setup.

**Comment by waddella** [comment]
please lower the priority of this issue, until you run into the issue yourself when working with the internal packages.

**Comment by waddella** [comment]
actually the error I observed came from `install_repo_add_sha`

**Comment by waddella** [comment]
Ok, I figured out the issues. its about upstream dependencies repetition, i.e. if you add `test.nest` and `utils.nest` as an upstream dependencies you get a modified chache error for `test.nest`

**Comment by nikolas-burkoff** [comment]
A bug in topological_sort:

![image](https://user-images.githubusercontent.com/15201933/127861130-2c277aab-8f4f-401d-8083-a3dd2c1fea6e.png)


6 elements going in -> 7 coming out (so test.nest is duplicated)
![image](https://user-images.githubusercontent.com/15201933/127860144-d81e8874-31e3-4357-a5eb-f083fdcada43.png)

![image](https://user-images.githubusercontent.com/15201933/127860338-a27513a8-5609-4739-8ab8-508a253895f0.png)

This is why we should have tests. 

See teal for a simpler topological sort which does not require recursion
