### ISSUE TITLE
install missing external dependencies

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#24]
Instead of throwing an error if external dependencies are missing, lets also install them with:

```r
remotes::install_deps(dependencies = TRUE, upgrade = "never")
```

as part of installing up-& down-stream internal dependencies (please make this conditional based on an argument).

also propagate the arguments to `remotes::install_deps` so that the `staged.dependency` function can control the upgrading strategy

**Comment by waddella** [comment]
@maximilianmordig can you do that in the next day, otherwise @nikolas-burkoff please prioritize this issue

**Comment by nikolas-burkoff** [comment]
I guess we want these to default to "yes install" so that the addins automatically install them as well?

**Comment by waddella** [comment]
Yes, by default external dependencies should be installed
