### ISSUE TITLE
investigate credentials package

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#27]
as proposed @nikolas-burkoff, please see https://ropensci.org/blog/2020/07/07/github-pat/ and update `README.md` if found useful

**Comment by maximilianmordig** [comment]
I tried this a while ago. This package uses `gert` for autheentication. Unfortunately, gert does not seem to work with non-public Github. I created an issue https://github.com/r-lib/gert/issues/145.

**Comment by nikolas-burkoff** [comment]
OK so with Max's comment above I don't think we need to confuse people mentioning credentials.

It does look a nice package though and one worth keeping an eye on.
