### ISSUE TITLE
remove current repo in staged_dependencies.yaml if

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#36]
that remote information can be placed into the `DESCRIPTION` file or the remote of the current upstream

**Comment by maximilianmordig** [comment]
Would keep it there. Otherwise, it seems that the (devtools) installation process may look there as well when it installs the dependencies themselves. See https://remotes.r-lib.org/

**Comment by nikolas-burkoff** [comment]
But you can get the remote by parsing this?
![image](https://user-images.githubusercontent.com/15201933/128011421-f2ad5754-a629-436c-860a-ad809897820c.png)
or
![image](https://user-images.githubusercontent.com/15201933/128011648-7eacb99f-a19a-416d-9494-1c0ee2d86ab0.png)

**Comment by waddella** [comment]
this is a problem with multiple remotes and forks, I will close this issue
