### ISSUE TITLE
Move example to public github and update README and roxygen examples

### ISSUE THREAD

**Issue by nikolas-burkoff** [openpharma/staged.dependencies#37]
README states:

See https://code.roche.com/maximilian_oliver.mordig/stageddeps.water and the related packages. 
Decide where they should be moved to - ideally somewhere where everyone who has access to staged.dependencies has read access to.

We should update README as well (can also then remove references to respectables and synthetic.rcdsic.data)

**Comment by maximilianmordig** [comment]
I have created repos on https://github.com/insightsengineering/stageddeps.water etc. However, I cannot add you (Nikolas) because you are currently not a member of that organization. I do not know if `insightsengineering` is made available to the public. If not, we should rather create these repos in the `openpharma` organization.
@dinakar29 What do you think?

**Comment by waddella** [comment]
please move them to `openpharma`, please ask Reinhold to create the repos.

**Comment by nikolas-burkoff** [comment]
Reinhold has been asked :)

**Comment by nikolas-burkoff** [comment]
@maximilianmordig - repos are now on openpharma so you can transfer the code across and update the README (I don't have access to the code in the repos)

**Comment by maximilianmordig** [comment]
I pushed the branches to 
https://github.com/openpharma/stageddeps.elecinfra
https://github.com/openpharma/stageddeps.electricity
https://github.com/openpharma/stageddeps.food
https://github.com/openpharma/stageddeps.garden
https://github.com/openpharma/stageddeps.house
https://github.com/openpharma/stageddeps.water

From there, one can create branches to test various workflows. 
`stageddeps.electricity` has an external dependency on `desc`.
`stageddeps.food` has an external dependency on `desc` and BioConductor's `SummarizedExperiment`.
All other dependencies are internal.
Intentionally, `stageddeps.garden` has no `staged_dependencies.yaml`.

**Comment by nikolas-burkoff** [comment]
Let's remove renv from the test repos please https://github.com/openpharma/staged.dependencies/pull/74#issuecomment-898366180
