### ISSUE TITLE
Re-running dependency_table produces error

### ISSUE THREAD

**Issue by nikolas-burkoff** [openpharma/staged.dependencies#38]
![image](https://user-images.githubusercontent.com/15201933/127840043-5f2ae1ad-4825-407a-bf34-c77455dc3237.png)

and then running it again produces a different error:

![image](https://user-images.githubusercontent.com/15201933/127841540-f9add927-a239-404f-93c4-c6f1fd9bb511.png)

**Comment by maximilianmordig** [comment]
I just tested this after freshly cloning `teal` using the `28renv@main` branch of `staged.dependencies`.
I also repeated it for `tern` and get no error. 
Maybe this error was also solved by the topological sort issue that you referenced above, although I had the impression that it was also working before.

```
> staged.dependencies::dependency_table()
                                        repo               host       type       branch
1                   insightsengineering/tern https://github.com    current local (main)
2                              Roche/rtables https://github.com   upstream         main
3             insightsengineering/utils.nest https://github.com   upstream         main
4                   insightsengineering/scda https://github.com   upstream         main
5              insightsengineering/test.nest https://github.com   upstream         main
6              insightsengineering/scda.2021 https://github.com   upstream         main
7                   insightsengineering/teal https://github.com downstream         main
8             insightsengineering/teal.devel https://github.com downstream         main
9  insightsengineering/teal.modules.clinical https://github.com downstream         main
10  insightsengineering/teal.modules.general https://github.com downstream         main
11           insightsengineering/teal.osprey https://github.com downstream         main
12          insightsengineering/teal.goshawk https://github.com downstream         main
13     insightsengineering/random.cdisc.data https://github.com      other         main
14                insightsengineering/osprey https://github.com      other         main
15               insightsengineering/goshawk https://github.com      other         main
16                insightsengineering/hermes https://github.com      other         main
17         insightsengineering/ggplot2.utils https://github.com      other         main
18   insightsengineering/teal.modules.hermes https://github.com      other         main
```
Running it twice gives the same output.

**Comment by maximilianmordig** [comment]
The error might come from `fs::dir_copy(local_dir, repo_dir)` although I make sure that `repo_dir` does not exist before executing this operation. Can you track this down to the function that causes this error (e.g. with `options(error = recover)`)? Unfortunately, I don't have Windows, and I think it might be due to this.

**Comment by nikolas-burkoff** [comment]
Yes I'll dig into it - I have to keep deleting my cache everytime :( - can you check without the packages being added to local.yaml and see if that works fine for you as well?

**Comment by nikolas-burkoff** [comment]
So on Windows it isn't deleting the local cached version directory (`unlink` is silently failing)

![image](https://user-images.githubusercontent.com/15201933/127990006-5074fcba-f4c4-4831-a6d2-d372ec01faf7.png)

Replacing `unlink(repo_dir, recursive = TRUE)` with `fs::dir_delete(repo_dir)` seems to fix it - my suspicion is this is something to do with long path names in Windows - I'll put a PR in for you to test @maximilianmordig
