### ISSUE TITLE
config.yaml is global

### ISSUE THREAD

**Issue by nikolas-burkoff** [openpharma/staged.dependencies#39]
We have `config.yaml` to store "local packages" but this is then fixed for all projects you are working on on your current machine (and if this list is different for different projects you'll need to keep editing it as you switch between them)

**Comment by maximilianmordig** [comment]
Yes, this is a design choice. If needed, we may change this by adding a field such as project path to the `config.yaml` so it knows to which project it applies and having separate blocks for each project (or each list of projects).

In my opinion, we can implement this later if users request it.
