### ISSUE TITLE
Graph sizing not working well

### ISSUE THREAD

**Issue by nikolas-burkoff** [openpharma/staged.dependencies#40]
The size seems fixed and not covering the whole viewer:

![image](https://user-images.githubusercontent.com/15201933/127843798-9cfbcfce-ca6e-4f63-867c-7480b0dd831a.png)

When I try to zoom in:
![image](https://user-images.githubusercontent.com/15201933/127843869-ecbd9c7d-5f55-4618-8366-467eefc727cf.png)

**Comment by maximilianmordig** [comment]
By hovering over the legend (right), you can also zoom it. I am not sure if visNetwork allows both the graph and legend zoom to be synchronized.
Was this what you meant?

**Comment by nikolas-burkoff** [comment]
Ah so this probably isn't an issue with our package but resizing the viewer does not change the size of the graph - so here I can see the graph or zoom in
![image](https://user-images.githubusercontent.com/15201933/128012920-916d6c5c-4df2-40b8-ae02-a209712b0ef8.png)

but if I change the size of the window the graph doesn't resize:
![image](https://user-images.githubusercontent.com/15201933/128013054-df606879-531b-44df-b8a8-5cef4c6e008c.png)

This does limit the usefulness of the graph imho

**Comment by nikolas-burkoff** [comment]
Closing as others have not commented this is a problem
