### ISSUE TITLE
Revert yaml files in NEST packages

### ISSUE THREAD

**Issue by nikolas-burkoff** [openpharma/staged.dependencies#44]
Now that #21 has been fixed

**Comment by waddella** [comment]
this depends on #17

**Comment by nikolas-burkoff** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/burn/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/burn/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Package | Direct upstream | Direct   downstream
-- | -- | --
rtables | Not   adding staged.dep yaml file for rtables
scda.2021 |   | scda,     tern,     osprey,     goshawk
scda | scda.2021 | tern,     osprey,     goshawk
test.nest |   | utils.nest,     rcd,     tern,     osprey,     goshawk,     teal,     teal.devel,     tmg,     tmc,     teal.osprey,     teal.goshawk,     hermes,     tmh
utils.nest | test.nest | rcd,     tern,     osprey,     goshawk,     teal,     teal.devel,     tmg,     tmc,     teal.osprey,     teal.goshawk,     ggplot2.utils,     hermes
rcd | test.nest,     utils.nest | teal,     teal.devel,     tmg,     tmc,     teal.osprey,     teal.goshawk
tern | test.nest,     utils.nest,     scda.2021,     scda,     rtables | osprey,     teal,     teal.devel,     tmg,     tmc,     teal.osprey,     teal.goshawk,     hermes
osprey | test.nest,     utils.nest,     scda.2021,     scda,     tern,     rtables | teal.osprey
goshawk | utils.nest,     test.nest,     scda,     scda.2021 | teal.goshawk
teal | utils.nest,     rcd,     tern,     test.nest,     rtables | teal.devel,     tmg,     tmc,     teal.osprey,     teal.goshawk,     tmh
teal.devel | utils.nest,     test.nest,     rcd,     tern,     teal | tmg,     tmc,     teal.osprey,     teal.goshawk,     tmh
tmg | test.nest,     utils.nest,     rcd,     tern,     teal,     teal.devel,     rtables |  
tmc | utils.nest,     test.nest,     rcd,     tern,     teal,     teal.devel,     rtables |  
teal.osprey | test.nest,     utils.nest,     tern,     rcd,     osprey,     teal,     teal.devel,     rtables |  
teal.goshawk | utils.nest,     test.nest,     tern,     rcd,     goshawk,     teal,     teal.devel |  
ggplot2.utils | utils.nest | hermes
hermes | utils.nest,     test.nest,     tern,     ggplot2.utils | tmh
tmh | test.nest,     teal,     teal.devel,     hermes |  



</body>

</html>

**Comment by nikolas-burkoff** [comment]
@maximilianmordig has pointed out this change should be on all branches...

**Comment by waddella** [comment]
It should be enough to do it on the main brach as all other branches should either start of main or have a common ancestor

**Comment by nikolas-burkoff** [comment]
All PRs merged and NEST team notified
