### ISSUE TITLE
Why do we specify direction of repos in yaml file?

### ISSUE THREAD

**Issue by nikolas-burkoff** [openpharma/staged.dependencies#45]
Surely this can be worked out from the DESCRIPTION files? We just need to know which packages are internal and their locations

**Comment by waddella** [comment]
There are a number of reasons:

1. The `staged_dependencies.yaml` specifies which packages are co-developed, i.e. not all packages listed in `DESCRIPTION` are staged dependencies
2. we need the remotes information
3. direct reverse dependencies are not listed in the `DESCRIPTION` file

**Comment by nikolas-burkoff** [comment]
@waddella question was "Why do we specify **direction** of repos in yaml file?" not why do we need a yaml file at all :)

I think we've discussed this and the answer was it is nice for users to separate them out - it also means we can calculate only upstream or downstream internal dependencies without looking at the DESCRIPTION files (of course there is nothing stopping users writing a yaml file with the dependencies directly contradicting the DESCRIPTION files :)
