### ISSUE TITLE
install packages with entrypoints

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#46]
if we have disconnected dependency graphs `install_all` should have an `entrypoints` (which defaults to current repo).

e.g.

```
install_all <- function(entrypoints = get_current_proj()) {
  ...
}
``` 

so that you could call

```
install_all(c("github.com/abc", "github.com/xyz"))
```

note this is related to #52

**Comment by maximilianmordig** [comment]
This can already be addressed with the function `install_deps`.

**Comment by nikolas-burkoff** [comment]
So I can't install dependencies from 2 separate (unconnected via yaml files) projects

![image](https://user-images.githubusercontent.com/15201933/129195389-39f91b9f-b247-468b-a508-ba140d87d364.png)
