### ISSUE TITLE
token matching

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#5]
please update the code and `README.md` to support a token lookup table. That is, I suggest to add an entry in `options` with a default mapping

```
options(staged.depencencies.token_mapping = c(
    "https://github.com" = "GITHUB_PAT", 
    "https://gitlab.com" = "GITLAB_PAT"
))
```

and then the user can modify it in the `.Rprofile`

**Comment by maximilianmordig** [comment]
Done
