### ISSUE TITLE
renv profile ignores custom .Rprofile

### ISSUE THREAD

**Issue by maximilianmordig** [openpharma/staged.dependencies#50]
renv profile seems nott to load the `~/.Rprofile` where I set my github pats etc. Where should users set these keys then?

**Comment by waddella** [comment]
does it work with the `~/.Renviron`?

**Comment by nikolas-burkoff** [comment]
So there is [here](https://rstudio.github.io/renv/reference/config.html)
![image](https://user-images.githubusercontent.com/15201933/128329362-cc185886-745c-4aa2-8404-af53ba582c4b.png)

**Comment by waddella** [comment]
ok, please update `README.md` if needed and close the issue.

**Comment by maximilianmordig** [comment]
Thanks, will update later. The solution is to put the following into `~/.Renviron`:
```
RENV_CONFIG_USER_PROFILE=TRUE
```
