### ISSUE TITLE
staged.dependencies::install_deps() - lack of message to the user

### ISSUE THREAD

**Issue by Polkas** [openpharma/staged.dependencies#53]
We find out that `staged.dependencies::install_deps()` is quite time consuming although the problem is lack of interaction with the user. Especially as the are not action on the screen for a long time. There should be some message to the user like `cat("Please wait, we preparing sth for you ... \n")`.

**Comment by nikolas-burkoff** [comment]
I believe there's a verbose argument to intall_deps which should tell you what's going on?

**Comment by Polkas** [comment]
Then it should not be deactivated on default.
