### ISSUE TITLE
make a staged dependency graph and text output

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#6]
# Graph

It would be good for any package that has a `staged_dependencies.yaml` file to allow to create a dependency graph that includes only other packages mentioned in the `staged_dependencies.yaml` files (recursively):

![staged dependencies (4)](https://user-images.githubusercontent.com/7786462/123103833-aa92c500-d436-11eb-9e35-428cc8781b68.png)

# Text output

Also, for command line use it would be good to add the `internal_dependencies` function that would look as follows:

```
staged_dependencies()

current branch: 01_fix@devel

repo        branch             rel
-------------------------------------------
B           devel               upstream
A           devel               upstream
C           01_fix@devel        upstream
D           01_fix@devel        current
E           devel               downstream
F           01_fix@devel        downstream
G           devel               downstream
H           devel               other
I           01_fix@devel        other
J           devel               other
K           devel               other
L           devel               downstream
```

Note the return object should be a `data.frame`.

**Comment by maximilianmordig** [comment]
done

**Comment by maximilianmordig** [comment]
visNetwork does not allow to easily place a label below a node, so the branch appears in a tooltip
