### ISSUE TITLE
Staged Dependencies: All Upstream Dependencies excluding this package - new feature request.

### ISSUE THREAD

**Issue by wwojciech** [openpharma/staged.dependencies#62]
Hi

I am using RStudio add-in to install all upstream dependencies. This features also tries to build and install my current package I am working on, and which is not ready.
Is there any way to create a separate add-in which installs all the upstream dependencies but without building the package I am currently working on?
Thanks

W.

**Comment by nikolas-burkoff** [comment]
For now if you run the command directly using the non-default argument `install_project = FALSE` you will skip installing the current package you are working on.

staged.dependencies::install_deps(project = ".", install_project = FALSE)

**Comment by wwojciech** [comment]
Thank you @nikolas-burkoff 
I assume that you will consider the solution for RStudio addin?

**Comment by wwojciech** [comment]
Hi @waddella @nikolas-burkoff 
Sometimes it is useful to install also project packet, so I would vote to have 2 addins.

W.
