### ISSUE TITLE
App add-on not working if missing visNetwork

### ISSUE THREAD

**Issue by pawelru** [openpharma/staged.dependencies#79]
![image](https://user-images.githubusercontent.com/12943682/130095368-16934fb6-6a04-44bc-91f0-58ac65cd2f90.png)

We need to put `visNetwork` into the package dependency.

**Comment by nikolas-burkoff** [comment]
So I'd rather leave visNetwork as a suggests as we don't need to install visNetwork for the bulk of the features of staged.dependencies and we don't want to have to install it for every automation run - but I agree this should be nicer than it is so will improve
